# Generated by Django 5.0.7 on 2025-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_role_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
