# Generated by Django 5.0.7 on 2025-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_service_from_blog_alter_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default='Ajibade', max_length=300),
            preserve_default=False,
        ),
    ]
