# Generated by Django 5.0.7 on 2025-02-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
