# Generated by Django 5.0.7 on 2025-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_image_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
